on:
  push:
    branches:
    - master

jobs:
  self-hosted-job:
    #runs-on: ubuntu-latest
    runs-on: self-hosted
    name: test
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Test
      run: |
        echo test
        docker ps
        docker run -it --rm ubuntu:latest bash -c 'echo docker test'
