on:
  push:
    branches:
    - master

jobs:
  self-hosted-job:
    #runs-on: ubuntu-latest
    runs-on: self-hosted
    #container: mumoshu/conflint:latest
    #container: rust:1.43.0
    services:
      db:
        image: postgres:10.1-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
        - 5432:5432
        # Add a health check
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    name: test
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Test
      run: |
        apt-get update -y
        apt-get install docker -y
        echo test
        docker ps
        docker run --rm ubuntu:latest bash -c 'echo docker test'
        echo USER=$USER
        echo "---"
        cut -d: -f1 /etc/passwd
        echo "---"
        whoami
        id $(whoami)
        ls -lah /var/run/docker.sock
